//! The native interface catalog, independent of which constructors a realm exposes.
//! Constructor specs and bridge installation add behavior to these identities;
//! they do not repeat interface names or inheritance.

use moli_webapi_declare::{BindError, WebApiInterfaceDescriptor};

macro_rules! interfaces {
    ($($name:ident $(= $js_name:literal)? $(: $parent:path)?;)+) => {
        moli_webapi_declare::declare_web_api_interfaces! {
            $(pub(crate) $name $(= $js_name)? $(: $parent)?;)+
        }

        pub(crate) fn descriptor(name: &str) -> std::option::Option<WebApiInterfaceDescriptor> {
            match name {
                $(<$name>::NAME => Some(<$name>::DESCRIPTOR),)+
                _ => None,
            }
        }
    };
}

interfaces! {
    AbortController;
    AbortSignal: EventTarget;
    AbstractRange;
    AnalyserNode;
    Animation;
    AnimationEffect;
    AnimationPlaybackEvent: Event;
    AnimationTimeline;
    Attr: Node;
    Audio;
    AudioBuffer;
    AudioContext: BaseAudioContext;
    AudioDestinationNode;
    AudioParam;
    AudioWorklet;
    AudioWorkletNode;
    BaseAudioContext: EventTarget;
    BatteryManager;
    BeforeUnloadEvent: Event;
    BiquadFilterNode;
    Blob;
    BroadcastChannel: EventTarget;
    ByteLengthQueuingStrategy;
    CDATASection: Text;
    CSSConditionRule: CSSGroupingRule;
    CSSContainerRule: CSSConditionRule;
    CSSCounterStyleRule: CSSRule;
    CSSFontFaceDescriptors: CSSStyleDeclaration;
    CSSFontFaceRule: CSSRule;
    CSSFontFeatureValuesMap;
    CSSFontFeatureValuesMapIterator = "CSSFontFeatureValuesMap Iterator";
    CSSFontFeatureValuesRule: CSSRule;
    CSSGroupingRule: CSSRule;
    CSSImportRule: CSSRule;
    CSSKeyframeRule: CSSRule;
    CSSKeyframesRule: CSSRule;
    CSSKeywordValue: CSSStyleValue;
    CSSLayerBlockRule: CSSGroupingRule;
    CSSLayerStatementRule: CSSRule;
    CSSMarginRule: CSSRule;
    CSSMediaRule: CSSConditionRule;
    CSSNamespaceRule: CSSRule;
    CSSNestedDeclarations: CSSRule;
    CSSNumericValue: CSSStyleValue;
    CSSPageDescriptors: CSSStyleDeclaration;
    CSSPageRule: CSSGroupingRule;
    CSSPropertyRule: CSSRule;
    CSSRule;
    CSSRuleList;
    CSSScopeRule: CSSGroupingRule;
    CSSStyleDeclaration;
    CSSStyleProperties: CSSStyleDeclaration;
    CSSStyleRule: CSSGroupingRule;
    CSSStyleSheet: StyleSheet;
    CSSStyleValue;
    CSSSupportsRule: CSSConditionRule;
    CSSUnitValue: CSSNumericValue;
    Cache;
    CacheStorage;
    CanvasGradient;
    CanvasPattern;
    CanvasRenderingContext2D;
    CapturedMouseEvent: Event;
    CaretPosition;
    CharacterData: Node;
    Client;
    Clients;
    Clipboard: EventTarget;
    ClipboardEvent: Event;
    ClipboardItem;
    CloseEvent: Event;
    CommandEvent: Event;
    Comment: CharacterData;
    CompositionEvent: UIEvent;
    CompressionStream;
    ContentVisibilityAutoStateChangeEvent: Event;
    CountQueuingStrategy;
    Crypto;
    CryptoKey;
    CustomElementRegistry;
    CustomEvent: Event;
    CustomStateSet;
    CustomStateSetIterator = "CustomStateSet Iterator";
    DOMError;
    DOMException;
    DOMImplementation;
    DOMMatrix: DOMMatrixReadOnly;
    DOMMatrixReadOnly;
    DOMParser;
    DOMPoint: DOMPointReadOnly;
    DOMPointReadOnly;
    DOMQuad;
    DOMRect: DOMRectReadOnly;
    DOMRectList;
    DOMRectReadOnly;
    DOMStringList;
    DOMStringMap;
    DOMTokenList;
    DataTransfer;
    DataTransferItem;
    DataTransferItemList;
    DecompressionStream;
    DedicatedWorkerGlobalScope: WorkerGlobalScope;
    DeprecatedStorageInfo;
    DeprecatedStorageQuota;
    Document: Node;
    DocumentFragment: Node;
    DocumentTimeline: AnimationTimeline;
    DocumentType: Node;
    DragEvent: MouseEvent;
    DynamicsCompressorNode;
    Element: Node;
    ElementInternals;
    ErrorEvent: Event;
    Event;
    EventCounts;
    EventCountsIterator = "EventCounts Iterator";
    EventSource: EventTarget;
    EventTarget;
    ExtendableEvent: Event;
    ExtendableMessageEvent: ExtendableEvent;
    FetchEvent: ExtendableEvent;
    File: Blob;
    FileList;
    FileReader: EventTarget;
    FileReaderSync;
    FileSystem;
    FileSystemDirectoryEntry: FileSystemEntry;
    FileSystemDirectoryHandle: FileSystemHandle;
    FileSystemDirectoryHandleAsyncIterator = "FileSystemDirectoryHandle AsyncIterator";
    FileSystemDirectoryReader;
    FileSystemEntry;
    FileSystemFileEntry: FileSystemEntry;
    FileSystemFileHandle: FileSystemHandle;
    FileSystemHandle;
    FileSystemSyncAccessHandle;
    FileSystemWritableFileStream: WritableStream;
    FocusEvent: UIEvent;
    FontFace;
    FontFaceSet;
    FontFaceSetIterator = "FontFaceSet Iterator";
    FontFaceSetLoadEvent: Event;
    FormData;
    FormDataIterator = "FormData Iterator";
    FormDataEvent: Event;
    Geolocation;
    GeolocationCoordinates;
    GeolocationPosition;
    GeolocationPositionError;
    HTMLAllCollection;
    HTMLAnchorElement: HTMLElement;
    HTMLAreaElement: HTMLElement;
    HTMLAudioElement: HTMLMediaElement;
    HTMLBRElement: HTMLElement;
    HTMLBaseElement: HTMLElement;
    HTMLBodyElement: HTMLElement;
    HTMLButtonElement: HTMLElement;
    HTMLCanvasElement: HTMLElement;
    HTMLCollection;
    HTMLDListElement: HTMLElement;
    HTMLDataElement: HTMLElement;
    HTMLDataListElement: HTMLElement;
    HTMLDetailsElement: HTMLElement;
    HTMLDialogElement: HTMLElement;
    HTMLDirectoryElement: HTMLElement;
    HTMLDivElement: HTMLElement;
    HTMLDocument: Document;
    HTMLElement: Element;
    HTMLEmbedElement: HTMLElement;
    HTMLFieldSetElement: HTMLElement;
    HTMLFontElement: HTMLElement;
    HTMLFormControlsCollection: HTMLCollection;
    HTMLFormElement: HTMLElement;
    HTMLFrameElement: HTMLElement;
    HTMLFrameSetElement: HTMLElement;
    HTMLHRElement: HTMLElement;
    HTMLHeadElement: HTMLElement;
    HTMLHeadingElement: HTMLElement;
    HTMLHtmlElement: HTMLElement;
    HTMLIFrameElement: HTMLElement;
    HTMLImageElement: HTMLElement;
    HTMLInputElement: HTMLElement;
    HTMLLIElement: HTMLElement;
    HTMLLabelElement: HTMLElement;
    HTMLLegendElement: HTMLElement;
    HTMLLinkElement: HTMLElement;
    HTMLMapElement: HTMLElement;
    HTMLMarqueeElement: HTMLElement;
    HTMLMediaElement: HTMLElement;
    HTMLMenuElement: HTMLElement;
    HTMLMetaElement: HTMLElement;
    HTMLMeterElement: HTMLElement;
    HTMLModElement: HTMLElement;
    HTMLOListElement: HTMLElement;
    HTMLObjectElement: HTMLElement;
    HTMLOptGroupElement: HTMLElement;
    HTMLOptionElement: HTMLElement;
    HTMLOptionsCollection: HTMLCollection;
    HTMLOutputElement: HTMLElement;
    HTMLParagraphElement: HTMLElement;
    HTMLParamElement: HTMLElement;
    HTMLPictureElement: HTMLElement;
    HTMLPreElement: HTMLElement;
    HTMLProgressElement: HTMLElement;
    HTMLQuoteElement: HTMLElement;
    HTMLScriptElement: HTMLElement;
    HTMLSelectElement: HTMLElement;
    HTMLSlotElement: HTMLElement;
    HTMLSourceElement: HTMLElement;
    HTMLSpanElement: HTMLElement;
    HTMLStyleElement: HTMLElement;
    HTMLTableCaptionElement: HTMLElement;
    HTMLTableCellElement: HTMLElement;
    HTMLTableColElement: HTMLElement;
    HTMLTableElement: HTMLElement;
    HTMLTableRowElement: HTMLElement;
    HTMLTableSectionElement: HTMLElement;
    HTMLTemplateElement: HTMLElement;
    HTMLTextAreaElement: HTMLElement;
    HTMLTimeElement: HTMLElement;
    HTMLTitleElement: HTMLElement;
    HTMLTrackElement: HTMLElement;
    HTMLUListElement: HTMLElement;
    HTMLUnknownElement: HTMLElement;
    HTMLVideoElement: HTMLMediaElement;
    HashChangeEvent: Event;
    Headers;
    HeadersIterator = "Headers Iterator";
    Highlight;
    HighlightIterator = "Highlight Iterator";
    HighlightRegistry;
    HighlightRegistryIterator = "HighlightRegistry Iterator";
    History;
    IDBCursor;
    IDBCursorWithValue: IDBCursor;
    IDBDatabase: EventTarget;
    IDBFactory;
    IDBIndex;
    IDBKeyRange;
    IDBObjectStore;
    IDBOpenDBRequest: IDBRequest;
    IDBRequest: EventTarget;
    IDBTransaction: EventTarget;
    IDBVersionChangeEvent: Event;
    IdleDeadline;
    IdleDetector: EventTarget;
    Image;
    ImageBitmap;
    ImageData;
    InputEvent: UIEvent;
    InterestEvent: Event;
    IntersectionObserver;
    IntersectionObserverEntry;
    KeyboardEvent: UIEvent;
    KeyframeEffect: AnimationEffect;
    Location;
    MathMLElement: Element;
    MediaCapabilities;
    MediaDevices: EventTarget;
    MediaError;
    MediaList;
    MediaQueryList;
    MediaQueryListEvent: Event;
    MediaSource: EventTarget;
    MemoryInfo;
    MessageChannel;
    MessageEvent: Event;
    MessagePort: EventTarget;
    MimeType;
    MimeTypeArray;
    MouseEvent: UIEvent;
    MutationObserver;
    MutationRecord;
    NamedNodeMap;
    NavigateEvent: Event;
    Navigation: EventTarget;
    NavigationActivation;
    NavigationCurrentEntryChangeEvent: Event;
    NavigationDestination;
    NavigationHistoryEntry: EventTarget;
    NavigationPrecommitController;
    NavigationPreloadManager;
    NavigationTransition;
    Navigator;
    NavigatorUAData;
    NetworkInformation: EventTarget;
    Node: EventTarget;
    NodeIterator;
    NodeList;
    Notification: EventTarget;
    NotificationEvent: ExtendableEvent;
    OfflineAudioCompletionEvent: Event;
    OfflineAudioContext: BaseAudioContext;
    OffscreenCanvas;
    OffscreenCanvasRenderingContext2D;
    Option;
    OscillatorNode;
    PageTransitionEvent: Event;
    Path2D;
    Performance: EventTarget;
    PerformanceEntry;
    PerformanceMark: PerformanceEntry;
    PerformanceMeasure: PerformanceEntry;
    PerformanceNavigation;
    PerformanceNavigationTiming: PerformanceEntry;
    PerformanceObserver;
    PerformanceObserverEntryList;
    PerformanceResourceTiming: PerformanceEntry;
    PerformanceTiming;
    PeriodicSyncEvent: ExtendableEvent;
    PeriodicSyncManager;
    PermissionStatus;
    Permissions;
    Plugin;
    PluginArray;
    PointerEvent: MouseEvent;
    PopStateEvent: Event;
    ProcessingInstruction: CharacterData;
    ProgressEvent: Event;
    PromiseRejectionEvent: Event;
    PushEvent: ExtendableEvent;
    PushManager;
    PushMessageData;
    PushSubscription;
    PushSubscriptionOptions;
    QuotaExceededError: DOMException;
    RTCDataChannel: EventTarget;
    RTCIceCandidate;
    RTCPeerConnection: EventTarget;
    RTCRtpReceiver;
    RTCSessionDescription;
    RadioNodeList: NodeList;
    Range: AbstractRange;
    ReadableByteStreamController;
    ReadableStream;
    ReadableStreamAsyncIterator = "ReadableStream AsyncIterator";
    ReadableStreamBYOBReader;
    ReadableStreamBYOBRequest;
    ReadableStreamDefaultController;
    ReadableStreamDefaultReader;
    Request;
    ResizeObserver;
    ResizeObserverEntry;
    ResizeObserverSize;
    Response;
    SVGAElement: SVGGraphicsElement;
    SVGAnimatedEnumeration;
    SVGAnimatedString;
    SVGAnimatedLength;
    SVGAnimatedLengthList;
    SVGAnimatedBoolean;
    SVGFEConvolveMatrixElement: SVGElement;
    SVGAngle;
    SVGAnimatedAngle;
    SVGMarkerElement: SVGElement;
    SVGAnimatedInteger;
    SVGAnimatedRect;
    SVGPreserveAspectRatio;
    SVGAnimatedPreserveAspectRatio;
    SVGAnimatedNumber;
    SVGAnimatedNumberList;
    SVGAnimatedTransformList;
    SVGCircleElement: SVGGeometryElement;
    SVGDefsElement: SVGGraphicsElement;
    SVGDescElement: SVGElement;
    SVGClipPathElement: SVGElement;
    SVGFilterElement: SVGElement;
    SVGMaskElement: SVGElement;
    SVGViewElement: SVGElement;
    SVGComponentTransferFunctionElement: SVGElement;
    SVGFEFuncAElement: SVGComponentTransferFunctionElement;
    SVGFEFuncBElement: SVGComponentTransferFunctionElement;
    SVGFEFuncGElement: SVGComponentTransferFunctionElement;
    SVGFEFuncRElement: SVGComponentTransferFunctionElement;
    SVGFEBlendElement: SVGElement;
    SVGFEColorMatrixElement: SVGElement;
    SVGFECompositeElement: SVGElement;
    SVGFEDisplacementMapElement: SVGElement;
    SVGFEMorphologyElement: SVGElement;
    SVGFETurbulenceElement: SVGElement;
    SVGTextPathElement: SVGTextContentElement;
    SVGFEDiffuseLightingElement: SVGElement;
    SVGFEDistantLightElement: SVGElement;
    SVGFEDropShadowElement: SVGElement;
    SVGFEGaussianBlurElement: SVGElement;
    SVGFEOffsetElement: SVGElement;
    SVGFEPointLightElement: SVGElement;
    SVGFESpecularLightingElement: SVGElement;
    SVGFESpotLightElement: SVGElement;
    SVGStopElement: SVGElement;
    SVGElement: Element;
    SVGEllipseElement: SVGGeometryElement;
    SVGForeignObjectElement: SVGGraphicsElement;
    SVGGElement: SVGGraphicsElement;
    SVGGeometryElement: SVGGraphicsElement;
    SVGGradientElement: SVGElement;
    SVGGraphicsElement: SVGElement;
    SVGImageElement: SVGGraphicsElement;
    SVGLength;
    SVGLengthList;
    SVGLineElement: SVGGeometryElement;
    SVGLinearGradientElement: SVGGradientElement;
    SVGMatrix: DOMMatrix;
    SVGMetadataElement: SVGElement;
    SVGNumber;
    SVGNumberList;
    SVGPathElement: SVGGeometryElement;
    SVGPatternElement: SVGElement;
    SVGPolygonElement: SVGGeometryElement;
    SVGPolylineElement: SVGGeometryElement;
    SVGRadialGradientElement: SVGGradientElement;
    SVGRect;
    SVGRectElement: SVGGeometryElement;
    SVGSVGElement: SVGGraphicsElement;
    SVGScriptElement: SVGElement;
    SVGStyleElement: SVGElement;
    SVGSymbolElement: SVGGraphicsElement;
    SVGTSpanElement: SVGTextPositioningElement;
    SVGTextContentElement: SVGGraphicsElement;
    SVGTextElement: SVGTextPositioningElement;
    SVGTextPositioningElement: SVGTextContentElement;
    SVGTitleElement: SVGElement;
    SVGUnitTypes;
    SVGStringList;
    SVGTransform;
    SVGTransformList;
    SVGUseElement: SVGGraphicsElement;
    Screen;
    ScreenOrientation: EventTarget;
    SecurityPolicyViolationEvent: Event;
    Selection;
    ServiceWorker: EventTarget;
    ServiceWorkerContainer;
    ServiceWorkerGlobalScope: WorkerGlobalScope;
    ServiceWorkerRegistration: EventTarget;
    ShadowRoot: DocumentFragment;
    SharedWorker: EventTarget;
    SharedWorkerGlobalScope: WorkerGlobalScope;
    SpeechSynthesis: EventTarget;
    SpeechSynthesisUtterance: EventTarget;
    SpeechSynthesisVoice;
    StaticRange: AbstractRange;
    Storage;
    StorageAccessHandle;
    StorageBucket;
    StorageBucketManager;
    StorageEstimate;
    StorageEvent: Event;
    StorageManager;
    StylePropertyMapReadOnly;
    StylePropertyMapReadOnlyIterator = "StylePropertyMapReadOnly Iterator";
    StyleSheet;
    StyleSheetList;
    SubmitEvent: Event;
    SubtleCrypto;
    SyncEvent: ExtendableEvent;
    SyncManager;
    Text: CharacterData;
    TextDecoder;
    TextDecoderStream;
    TextEncoder;
    TextEncoderStream;
    TextEvent: UIEvent;
    TextMetrics;
    TextTrack: EventTarget;
    TextTrackCue: EventTarget;
    TextTrackCueList;
    TextTrackList: EventTarget;
    ToggleEvent: Event;
    Touch;
    TouchEvent: UIEvent;
    TouchList;
    TrackEvent: Event;
    TransformStream;
    TransformStreamDefaultController;
    TreeWalker;
    TrustedHTML;
    TrustedScript;
    TrustedScriptURL;
    TrustedTypePolicy;
    TrustedTypePolicyFactory;
    UIEvent: Event;
    URL;
    URLSearchParams;
    URLSearchParamsIterator = "URLSearchParams Iterator";
    UserActivation;
    VTTCue: TextTrackCue;
    ValidityState;
    ViewTransition;
    ViewTransitionTypeSet;
    ViewTransitionTypeSetIterator = "ViewTransitionTypeSet Iterator";
    VisualViewport: EventTarget;
    WEBGLDebugRendererInfo = "WEBGL_debug_renderer_info";
    WEBGLLoseContext = "WEBGL_lose_context";
    WebGL2RenderingContext;
    WebGLBuffer: WebGLObject;
    WebGLFramebuffer: WebGLObject;
    WebGLObject;
    WebGLProgram: WebGLObject;
    WebGLRenderbuffer: WebGLObject;
    WebGLRenderingContext;
    WebGLShader: WebGLObject;
    WebGLShaderPrecisionFormat;
    WebGLUniformLocation;
    WebSocket: EventTarget;
    WebSocketError: DOMException;
    WebSocketStream;
    WheelEvent: MouseEvent;
    Window: EventTarget;
    WindowClient: Client;
    Worker: EventTarget;
    WorkerGlobalScope: EventTarget;
    WorkerLocation;
    WorkerNavigator;
    WritableStream;
    WritableStreamDefaultController;
    WritableStreamDefaultWriter;
    XMLDocument: Document;
    XMLHttpRequest: XMLHttpRequestEventTarget;
    XMLHttpRequestEventTarget: EventTarget;
    XMLHttpRequestUpload: XMLHttpRequestEventTarget;
    XMLSerializer;
    XPathEvaluator;
    XPathResult;
}

/// Resolve dynamic native factory choices through the same catalog as derives.
/// `name` must come from native metadata, never a JavaScript prototype or tag.
pub(crate) fn initialize<'s>(
    scope: &mut v8::PinScope<'s, '_>,
    object: v8::Local<'s, v8::Object>,
    name: &str,
) -> Result<(), BindError> {
    descriptor(name)
        .ok_or_else(|| BindError::new(format!("unknown native interface `{name}`")))?
        .initialize(scope, object)
}
