// Regenerate the offline reference corpus from the pinned Turndown checkout.
// See README.md in this directory for dependencies and invocation.
import assert from 'node:assert/strict';
import { execFileSync } from 'node:child_process';
import { createRequire } from 'node:module';
import { readFileSync, writeFileSync, mkdtempSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const revision = 'aa84dfa3e2361edea8c43acbfc2b7a9363494bfd';
const upstream = resolve(process.argv[2]);
assert.equal(execFileSync('git', ['rev-parse', 'HEAD'], { cwd: upstream, encoding: 'utf8' }).trim(), revision);
const require = createRequire(join(upstream, 'package.json'));
const domino = require('@mixmark-io/domino');
assert.equal(require('@mixmark-io/domino/package.json').version, '2.2.0');
const destination = dirname(fileURLToPath(import.meta.url));
const temporary = mkdtempSync(join(tmpdir(), 'moli-turndown-esm-'));
try {
  // Node's ESM loader needs file extensions; Turndown's build normally supplies
  // these through Rollup. Only import paths and CommonJS require setup change.
  for (const name of ['collapse-whitespace', 'commonmark-rules', 'html-parser', 'node', 'root-node', 'rules', 'turndown', 'utilities']) {
    const original = readFileSync(join(upstream, 'src', name + '.js'), 'utf8');
    const source = original.replace(/from '(\.\/[^']+)'/g, "from '$1.mjs'");
    const header = `import { createRequire } from 'node:module';\nconst require = createRequire(${JSON.stringify(join(upstream, 'package.json'))});\n`;
    writeFileSync(join(temporary, name + '.mjs'), header + source);
  }
  const { default: Turndown } = await import(pathToFileURL(join(temporary, 'turndown.mjs')));
  const options = {
    headingStyle: 'atx', hr: '---', bulletListMarker: '-',
    codeBlockStyle: 'fenced', fence: '```', emDelimiter: '*',
    strongDelimiter: '**', linkStyle: 'inlined', br: '  ',
  };
  const document = domino.createDocument(readFileSync(join(upstream, 'test', 'index.html'), 'utf8'));
  const upstreamCases = Array.from(document.querySelectorAll('.case')).map((node, index) => ({
    id: `upstream_${String(index + 1).padStart(3, '0')}`,
    name: node.getAttribute('data-name'),
    html: node.querySelector('.input').innerHTML,
    original_options: JSON.parse(node.getAttribute('data-options') || '{}'),
  }));
  const extra = JSON.parse(readFileSync(join(destination, 'additional.json'), 'utf8'));
  const cases = [...upstreamCases, ...extra].map(test => {
    const preformattedCode = test.original_options?.preformattedCode || false;
    const reference = new Turndown({ ...options, preformattedCode });
    return { ...test, preformatted_code: preformattedCode, markdown: reference.turndown(test.html) };
  });
  const corpus = {
    upstream: { repository: 'https://github.com/mixmark-io/turndown', revision, version: '7.2.4', domino: '2.2.0' },
    options,
    cases,
  };
  writeFileSync(join(destination, 'cases.json'), JSON.stringify(corpus, null, 2) + '\n');
  writeFileSync(join(destination, 'LICENSE'), readFileSync(join(upstream, 'LICENSE')));
  writeFileSync(join(destination, 'cases.rs'), '// Generated by generate.mjs. See README.md and LICENSE.\n' + cases.map((test, index) => `case!(${test.id}, ${index});`).join('\n') + '\n');
  console.log(`Generated ${upstreamCases.length} upstream cases and ${extra.length} additional cases.`);
} finally {
  rmSync(temporary, { recursive: true, force: true });
}
