use std::{fmt::Write as _, fs::File, io::BufReader, path::Path};

use anyhow::{Context, Result};
use moli_cookie_jar::{StoredCookie, StoredCookieSameSite, StoredCookieSourceScheme};
use time::OffsetDateTime;

use crate::atomic_file::write_file_atomically;

const NETSCAPE_COOKIE_FILE_HEADER: &str = "# Netscape HTTP Cookie File\n\
# This file was generated by Moli. Do not edit.\n\n";

#[derive(Debug, Clone, Copy, Default, PartialEq, Eq)]
pub struct CookieFileSaveReport {
    pub written: usize,
    pub skipped_expired: usize,
    pub skipped_partitioned: usize,
}

pub fn load_cookie_file(path: impl AsRef<Path>) -> Result<Vec<StoredCookie>> {
    let path = path.as_ref();
    let file = File::open(path)
        .with_context(|| format!("failed to open cookie file `{}`", path.display()))?;
    parse_netscape_cookie_file(BufReader::new(file))
        .with_context(|| format!("failed to parse cookie file `{}`", path.display()))
}

/// Saves unexpired, unpartitioned cookies in the interoperable Netscape format.
///
/// Netscape cookie files cannot represent partition keys, so partitioned
/// cookies are deliberately omitted instead of broadening their scope on a
/// later import. The returned report describes written and omitted records.
pub fn save_cookie_file(
    path: impl AsRef<Path>,
    cookies: impl IntoIterator<Item = StoredCookie>,
) -> Result<CookieFileSaveReport> {
    let path = path.as_ref();
    let mut output = NETSCAPE_COOKIE_FILE_HEADER.to_owned();
    let mut report = CookieFileSaveReport::default();

    for cookie in cookies {
        if cookie.is_expired() {
            report.skipped_expired += 1;
            continue;
        }
        if cookie.partition_key.is_some() {
            report.skipped_partitioned += 1;
            continue;
        }
        append_netscape_cookie(&mut output, &cookie)?;
        report.written += 1;
    }

    write_file_atomically(path, output.as_bytes(), "cookie jar")?;
    Ok(report)
}

fn append_netscape_cookie(output: &mut String, cookie: &StoredCookie) -> Result<()> {
    let domain = cookie.domain.trim_start_matches('.');
    anyhow::ensure!(!domain.is_empty(), "cookie domain is empty");
    anyhow::ensure!(!cookie.name.is_empty(), "cookie name is empty");
    anyhow::ensure!(
        cookie.path.starts_with('/'),
        "cookie path must start with `/`"
    );
    for (field, value) in [
        ("domain", domain),
        ("path", cookie.path.as_str()),
        ("name", cookie.name.as_str()),
        ("value", cookie.value.as_str()),
    ] {
        anyhow::ensure!(
            !value.contains(['\t', '\r', '\n']),
            "cookie {field} cannot be represented in a Netscape cookie file"
        );
    }

    if cookie.http_only {
        output.push_str("#HttpOnly_");
    }
    if !cookie.host_only {
        output.push('.');
    }
    output.push_str(domain);
    let tail_match = if cookie.host_only { "FALSE" } else { "TRUE" };
    let secure = if cookie.secure { "TRUE" } else { "FALSE" };
    let expires = cookie
        .expires
        .map(|expires| expires.unix_timestamp())
        .unwrap_or(0);
    writeln!(
        output,
        "\t{tail_match}\t{}\t{secure}\t{expires}\t{}\t{}",
        cookie.path, cookie.name, cookie.value
    )
    .expect("writing to a String cannot fail");
    Ok(())
}

pub(crate) fn parse_netscape_cookie_file(
    reader: impl std::io::BufRead,
) -> Result<Vec<StoredCookie>> {
    let mut cookies = Vec::new();
    for parsed in netscape_cookie_file_parser::parse(reader)? {
        let cookie = stored_cookie_from_netscape_cookie(parsed, cookies.len() as u64)?;
        if !cookie.is_expired() {
            cookies.push(cookie);
        }
    }
    Ok(cookies)
}

fn stored_cookie_from_netscape_cookie(
    cookie: netscape_cookie_file_parser::Cookie,
    creation_index: u64,
) -> Result<StoredCookie> {
    let secure = cookie.secure;
    let name = utf8_cookie_field("name", cookie.name)?;
    anyhow::ensure!(!name.is_empty(), "cookie name is empty");
    let domain = utf8_cookie_field("domain", cookie.domain)?.to_ascii_lowercase();
    anyhow::ensure!(!domain.is_empty(), "cookie domain is empty");
    let path = utf8_cookie_field("path", cookie.path)?;
    anyhow::ensure!(path.starts_with('/'), "cookie path must start with `/`");

    Ok(StoredCookie {
        name,
        value: utf8_cookie_field("value", cookie.value)?,
        domain,
        host_only: !cookie.tail_match,
        path,
        secure,
        http_only: cookie.http_only,
        expires: parse_netscape_expires(cookie.expires)?,
        same_site: StoredCookieSameSite::Unspecified,
        priority: None,
        partition_key: None,
        source_scheme: if secure {
            StoredCookieSourceScheme::Secure
        } else {
            StoredCookieSourceScheme::NonSecure
        },
        source_port: -1,
        creation_index,
        last_access_index: 0,
    })
}

fn utf8_cookie_field(field: &'static str, value: Vec<u8>) -> Result<String> {
    String::from_utf8(value).with_context(|| format!("cookie {field} is not valid UTF-8"))
}

fn parse_netscape_expires(timestamp: u64) -> Result<Option<OffsetDateTime>> {
    if timestamp == 0 {
        return Ok(None);
    }
    let timestamp = i64::try_from(timestamp).context("cookie expiry timestamp is too large")?;
    Ok(Some(OffsetDateTime::from_unix_timestamp(timestamp)?))
}
