(() => {
    const check = (ok, message) => { if (!ok) throw new Error(message); };
    const unit = (value, number, name, message) => {
        check(value instanceof CSSUnitValue && value.value === number && value.unit === name,
              message + ': ' + String(value));
    };
    const parent = document.createElement('div');
    parent.style.cssText = 'width: 800px; font-size: 10px; --inherited: 12px;';
    const element = document.createElement('div');
    parent.append(element); document.body.append(parent);
    const map = element.computedStyleMap();
    check(map === element.computedStyleMap(), 'same map');
    element.style.cssText = 'width:calc(25% + 2em);height:50%;margin-left:auto;transition-property:none;transition-duration:1s,2s;';
    let width = map.get('width');
    check(width instanceof CSSMathSum && width.values.length === 2, 'computed sum');
    unit(width.values[0], 25, 'percent', 'percentage kept');
    unit(width.values[1], 20, 'px', 'relative units computed');
    check(width.type().length === 1 && width.type().percentHint === 'length', 'computed type');
    unit(map.get('height'), 50, 'percent', 'percentage is not a used size');
    check(map.get('margin-left') instanceof CSSKeywordValue && map.get('margin-left').value === 'auto', 'auto kept');
    const times = map.getAll('transition-duration');
    check(times.length === 2, 'native list cardinality');
    unit(times[0], 1, 's', 'first duration'); unit(times[1], 2, 's', 'second duration');
    check(map.get('--inherited') instanceof CSSUnparsedValue && String(map.get('--inherited')) === '12px', 'computed custom tokens');
    check(map.get('--absent') === undefined && map.getAll('--absent').length === 0, 'absent custom property');
    check(Object.getPrototypeOf(map.get('margin')) === CSSStyleValue.prototype, 'shorthand stays opaque');
    check(Object.getPrototypeOf(map.get('color')) === CSSStyleValue.prototype, 'unsupported value stays opaque');
    width.values[1].value = 999;
    unit(map.get('width').values[1], 20, 'px', 'fresh value does not mutate style');
    parent.style.fontSize = '20px';
    unit(map.get('width').values[1], 40, 'px', 'retained map observes inherited changes');
    element.style.width = 'clamp(1px, 50%, 3em)';
    width = map.get('width');
    check(width instanceof CSSMathClamp, 'computed clamp');
    unit(width.lower, 1, 'px', 'lower'); unit(width.value, 50, 'percent', 'preferred'); unit(width.upper, 60, 'px', 'upper');
    element.style.width = 'min(5%, 3em)';
    width = map.get('width');
    check(width instanceof CSSMathMin && width.values.length === 2, 'computed min');
    unit(width.values[0], 5, 'percent', 'min percentage'); unit(width.values[1], 60, 'px', 'min length');
    element.style.width = 'calc(1px + 0%)';
    width = map.get('width');
    check(width instanceof CSSMathSum && width.values.length === 2, 'zero percentage stays in the computed sum');
    unit(width.values[0], 0, 'percent', 'zero percentage'); unit(width.values[1], 1, 'px', 'absolute length');
    element.style.width = 'calc(1in + 2px)'; unit(map.get('width'), 98, 'px', 'computed absolute sum');
    element.style.width = 'calc(-1px)'; unit(map.get('width'), 0, 'px', 'computed numeric range');
    element.style.opacity = 'calc(2)'; unit(map.get('opacity'), 1, 'number', 'computed opacity range');
    element.style.width = 'calc(10% + 1px)';
    const iterated = new Map(map).get('width')[0];
    check(iterated instanceof CSSMathSum && String(iterated) === String(map.get('width')), 'iterator uses native values');
    const other = document.getElementById('child').contentWindow;
    const childElement = other.document.createElement('div'); other.document.body.append(childElement);
    childElement.style.width = 'calc(10% + 2px)';
    const childMap = childElement.computedStyleMap();
    const read = StylePropertyMapReadOnly.prototype.get;
    const childValue = read.call(childMap, 'width');
    check(childValue instanceof other.CSSMathSum && !(childValue instanceof CSSMathSum), 'map realm');
    check(childValue.values[0] instanceof other.CSSUnitValue, 'operand realm');
    const NativeSum = other.CSSMathSum;
    other.CSSMathSum = () => { throw new Error('author constructor'); };
    check(read.call(childMap, 'width') instanceof NativeSum, 'intrinsic allocation');
    other.CSSMathSum = NativeSum;
    parent.remove(); childElement.remove();
    check(map.get('width') === undefined && !map.has('width'), 'detached map empty');
    return true;
})()
