(async () => {
  const checks=[];
  globalThis.__codecChecks=checks;
  const eq=(a,b)=>{if(!Object.is(a,b))throw Error(`expected ${b}, got ${a}`)};
  const bytes=(a,b)=>eq(Array.from(a).join(),Array.from(b).join());
  const check=async(name,run)=>{globalThis.__codecCurrentCheck=name;try{await run();checks.push({name,passed:true})}catch(error){checks.push({name,passed:false,error:String(error),stack:error.stack})}};
  const throws=(realm,name,run)=>{let e;try{run()}catch(error){e=error}if(!e||e.name!==name||!(e instanceof realm[name==='TypeError'?'TypeError':'DOMException']))throw Error(`expected ${name}, got ${e}`);return e};
  const rejects=async(realm,name,run)=>{let promise;try{promise=run()}catch(e){throw Error('must reject, not throw: '+e)}eq(promise instanceof realm.Promise,true);let error;try{await promise}catch(e){error=e}if(!error||error.name!==name)throw Error(`expected rejected ${name}, got ${error}`)};
  if(typeof document!=='undefined'&&!document.getElementById('child')){const child=document.createElement('iframe');child.id='child';document.body.append(child)}
  const realms=[globalThis];if(typeof document!=='undefined')realms.push(document.getElementById('child').contentWindow);
  for(const [ri,r] of realms.entries()){
    const C=r.VideoFrame,init=(over={})=>({format:'RGBA',codedWidth:2,codedHeight:2,timestamp:-17,duration:3,...over});
    const frame=(over={})=>new C(new Uint8Array([255,0,0,255,0,255,0,255,0,0,255,255,255,255,255,255]),init(over));
    const test=(name,run)=>check(`${ri}: ${name}`,run);
    await test('descriptors and constructor',()=>{
      eq(C.length,1);eq(C.name,'VideoFrame');eq(Object.getPrototypeOf(C),r.Function.prototype);eq(Object.getPrototypeOf(C.prototype),r.Object.prototype);
      const d=Object.getOwnPropertyDescriptor(r,'VideoFrame');eq(d.enumerable,false);eq(d.writable,true);eq(d.configurable,true);
      for(const [name,length]of [['allocationSize',0],['copyTo',1],['clone',0],['close',0],['metadata',0]]){const d=Object.getOwnPropertyDescriptor(C.prototype,name);eq(typeof d.value,'function');eq(d.value.length,length);eq(d.enumerable,true);eq(d.writable,true);eq(d.configurable,true)}
      for(const name of ['format','codedWidth','codedHeight','codedRect','visibleRect','displayWidth','displayHeight','rotation','flip','timestamp','duration','colorSpace']){const d=Object.getOwnPropertyDescriptor(C.prototype,name);eq(typeof d.get,'function');eq(d.set,undefined);eq(d.enumerable,true);eq(d.configurable,true)}
      eq(Object.prototype.toString.call(frame()),'[object VideoFrame]');
    });
    await test('requires new without conversion',()=>{let n=0;throws(r,'TypeError',()=>C(new Proxy({}, {get(){n++}})));eq(n,0)});
    for(const [index,source] of [undefined,null,{},[],1,'frame',new Proxy(new Uint8Array(16),{})].entries())await test('invalid source '+index,()=>throws(r,'TypeError',()=>new C(source,init())));
    await test('bytes are a view snapshot',async()=>{const source=new Uint8Array(20);source.set([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16],2);const f=new C(new DataView(source.buffer,2,16),init());source.fill(0);const dst=new Uint8Array(18).fill(99);const layout=await f.copyTo(new DataView(dst.buffer,1,16));bytes(dst,[99,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,99]);eq(layout[0].stride,8);f.close()});
    const formats=['I420','I420P10','I420P12','I420A','I420AP10','I420AP12','I422','I422P10','I422P12','I422A','I422AP10','I422AP12','I444','I444P10','I444P12','I444A','I444AP10','I444AP12','NV12','RGBA','RGBX','BGRA','BGRX'];
    for(const format of formats)await test('raw odd planes and row padding '+format,async()=>{
      const rgb=/^[RB]G[BR][AX]$/.test(format),wide=/P1[02]$/.test(format),b=wide?2:1,subx=/^I44/.test(format)?1:2,suby=/^I420/.test(format)?2:1;
      let specs=rgb?[[3,3,4]]:[[3,3,b],[Math.ceil(3/subx),Math.ceil(3/suby),b],[Math.ceil(3/subx),Math.ceil(3/suby),b]];
      if(format==='NV12')specs=[[3,3,1],[2,2,2]];else if(!rgb&&format.includes('A'))specs.push([3,3,b]);
      let end=0;const sourceLayout=specs.map(([w,h,b])=>{const p={offset:end+2,stride:w*b+3};end=p.offset+p.stride*h;return p});
      const source=new Uint8Array(end).map((_,i)=>(i*13+5)&255);const f=new C(source,init({format,codedWidth:3,codedHeight:3,layout:sourceLayout}));
      const compact=[];for(let i=0;i<specs.length;i++){const[w,h,b]=specs[i],p=sourceLayout[i];for(let y=0;y<h;y++)compact.push(...source.slice(p.offset+y*p.stride,p.offset+y*p.stride+w*b))}
      eq(f.allocationSize(),compact.length);const target=new Uint8Array(compact.length);await f.copyTo(target);bytes(target,compact);
      const padded=new Uint8Array(end+4).fill(77);const layout=await f.copyTo(padded,{layout:sourceLayout});eq(layout.length,specs.length);
      const expected=new Uint8Array(end+4).fill(77);for(let i=0;i<specs.length;i++){const[w,h,b]=specs[i],p=sourceLayout[i];for(let y=0;y<h;y++)expected.set(source.slice(p.offset+y*p.stride,p.offset+y*p.stride+w*b),p.offset+y*p.stride)}bytes(padded,expected);
      const clone=f.clone();f.close();eq(clone.format,format);const copied=new Uint8Array(compact.length);await clone.copyTo(copied);bytes(copied,compact);clone.close();
    });
    await test('crop permits copying coded padding',async()=>{const f=frame({visibleRect:{x:1,y:0,width:1,height:2}});eq(f.allocationSize(),8);const dst=new Uint8Array(8);await f.copyTo(dst);bytes(dst,[0,255,0,255,255,255,255,255]);eq(f.allocationSize({rect:f.codedRect}),f.codedWidth*f.codedHeight*4);f.close()});
    for(const over of [{codedWidth:0},{codedHeight:0},{codedWidth:2**32},{format:'invalid'},{timestamp:Infinity},{duration:-1},{displayWidth:1},{displayHeight:1},{displayWidth:0,displayHeight:1},{visibleRect:{x:-1,width:1,height:1}},{visibleRect:{x:.5,width:1,height:1}},{visibleRect:{width:0,height:1}},{visibleRect:{x:2,width:1,height:1}},{rotation:Infinity},{layout:[]},{layout:[{offset:0,stride:1}]}])await test('invalid init '+JSON.stringify(over),()=>throws(r,'TypeError',()=>frame(over)));
    await test('layout overlap and overflow',()=>{for(const layout of [[{offset:0,stride:2},{offset:0,stride:1},{offset:5,stride:1}],[{offset:2**32-1,stride:2},{offset:0,stride:1},{offset:1,stride:1}]])throws(r,'TypeError',()=>new C(new Uint8Array(6),init({format:'I420',layout}))) });
    await test('shared storage and byte offsets',async()=>{if(typeof r.SharedArrayBuffer!=='function')return;const ab=new r.SharedArrayBuffer(20),source=new Uint8Array(ab,2,16);source.fill(17);const f=new C(source,init());source.fill(0);await f.copyTo(source);bytes(source,new Uint8Array(16).fill(17));eq(new Uint8Array(ab)[0],0);f.close()});
    await test('newTarget prototype follows conversion and precedes transfer',()=>{const b=new Uint8Array(16),log=[],sentinel={};const options=init({transfer:[b.buffer],get timestamp(){log.push('convert');return 2}});const Target=new Proxy(function(){},{get(target,key,receiver){if(key==='prototype'){log.push('prototype');throw sentinel}return Reflect.get(target,key,receiver)}});let caught;try{Reflect.construct(C,[b,options],Target)}catch(e){caught=e}eq(caught,sentinel);eq(log.join(),'convert,prototype');eq(b.byteLength,16)});
    await test('transfer snapshots before detaching',async()=>{const b=new Uint8Array(16).fill(42),f=new C(b,init({transfer:[b.buffer]}));eq(b.byteLength,0);const copy=new Uint8Array(16);await f.copyTo(copy);bytes(copy,new Uint8Array(16).fill(42));f.close()});
    await test('duplicate transfer does not detach',()=>{const b=new ArrayBuffer(16);throws(r,'DataCloneError',()=>new C(b,init({transfer:[b,b]})));eq(b.byteLength,16)});
    await test('late dictionary detachment is observed',()=>{const b=new ArrayBuffer(16);throws(r,'TypeError',()=>new C(b,init({get visibleRect(){structuredClone(b,{transfer:[b]});return undefined}})))});
    await test('late dictionary mutation is observed',async()=>{const b=new Uint8Array(16);const f=new C(b,init({get timestamp(){b.fill(29);return 1}}));const d=new Uint8Array(16);await f.copyTo(d);bytes(d,b);f.close()});
    await test('null dictionaries and options',()=>{throws(r,'TypeError',()=>new C(new Uint8Array(16),null));const f=frame();eq(f.allocationSize(null),16);f.close()});
    await test('clone has independent lifetime and native metadata',async()=>{const f=frame(),clone=f.clone();Object.defineProperties(f,{codedWidth:{value:100},format:{value:'I420'},timestamp:{value:0}});f.close();eq(clone.timestamp,-17);eq(clone.codedWidth,2);eq(clone.format,'RGBA');eq(clone.colorSpace.primaries,'bt709');eq(clone.colorSpace.matrix,'rgb');const dst=new Uint8Array(16);await clone.copyTo(dst);eq(dst[0],255);clone.close()});
    await test('close is idempotent and resets geometry',()=>{const f=frame({rotation:90,flip:true});f.close();f.close();eq(f.format,null);eq(f.codedRect,null);eq(f.visibleRect,null);eq(f.codedWidth,0);eq(f.codedHeight,0);eq(f.displayWidth,0);eq(f.displayHeight,0);eq(f.rotation,0);eq(f.flip,false);eq(f.timestamp,-17);eq(f.duration,3);for(const k of ['matrix','primaries','transfer','fullRange'])eq(f.colorSpace[k],null);throws(r,'InvalidStateError',()=>f.clone());throws(r,'InvalidStateError',()=>f.metadata());throws(r,'InvalidStateError',()=>f.allocationSize())});
    await test('computed display size rounds to zero',()=>{const f=new C(new Uint8Array(8*8*4),init({codedWidth:8,codedHeight:8,displayWidth:1,displayHeight:1}));throws(r,'TypeError',()=>new C(f,{visibleRect:{width:1,height:1}}));eq(f.displayWidth,1);f.close()});
    await test('sRGB red copies into display-p3 without Canvas conversion',async()=>{const f=new C(new Uint8Array([255,0,0,255]),{format:'RGBA',codedWidth:1,codedHeight:1,timestamp:0}),out=new Uint8Array(4);await f.copyTo(out,{format:'RGBA',colorSpace:'display-p3'});for(const [i,want]of [234,51,35,255].entries())if(Math.abs(out[i]-want)>1)throw Error(`channel ${i}: ${out[i]} vs ${want}`);f.close()});
    await test('encoder exposure and closed frame TypeError precedes codec state',()=>{if(!r.isSecureContext){eq('VideoEncoder' in r,false);return}const e=new r.VideoEncoder({output(){},error(){}}),f=frame();throws(r,'InvalidStateError',()=>e.encode(f));f.close();throws(r,'TypeError',()=>e.encode(f));const late=frame();throws(r,'TypeError',()=>e.encode(late,{get keyFrame(){late.close();return false}}));eq(e.encodeQueueSize,0);e.close();throws(r,'TypeError',()=>e.encode(f))});
    await test('copy errors reject',async()=>{const f=frame();await rejects(r,'TypeError',()=>f.copyTo(new Uint8Array(1)));await rejects(r,'TypeError',()=>f.copyTo({}));await rejects(r,'NotSupportedError',()=>f.copyTo(new Uint8Array(16),{format:'I420'}));f.close();await rejects(r,'InvalidStateError',()=>f.copyTo(new Uint8Array(16)))});
    await test('copy rechecks frame after options conversion',async()=>{const f=frame();await rejects(r,'InvalidStateError',()=>f.copyTo(new Uint8Array(16),{get rect(){f.close();return undefined}}))});
    await test('copy rechecks destination after options conversion',async()=>{const f=frame(),b=new ArrayBuffer(16);await rejects(r,'TypeError',()=>f.copyTo(b,{get rect(){structuredClone(b,{transfer:[b]});return undefined}}));f.close()});
    for(const name of ['clone','close','metadata','allocationSize','copyTo'])await test('receiver precedes conversion '+name,async()=>{const f=frame(),revoked=Proxy.revocable(f,{});revoked.revoke();let conversions=0;const arg=new Proxy({}, {get(){conversions++;throw Error('converted')}});for(const receiver of [{},Object.create(C.prototype),Object.create(f),new Proxy(f,{}),revoked.proxy]){if(name==='copyTo')await rejects(r,'TypeError',()=>C.prototype[name].call(receiver,arg,arg));else throws(r,'TypeError',()=>C.prototype[name].call(receiver,arg));}eq(conversions,0);f.close()});
    await test('cross realm geometry and color use method realm',()=>{const f=frame(),get=Object.getOwnPropertyDescriptor(C.prototype,'visibleRect').get;const rect=get.call(f);eq(Object.getPrototypeOf(rect),r.DOMRectReadOnly.prototype);eq(Object.getPrototypeOf(f.clone()),C.prototype);eq(Object.getPrototypeOf(f.colorSpace),r.VideoColorSpace.prototype);f.close()});
    for(const rotation of [-315,-90,0,44,45,90,180,270,360,1e300])await test('orientation '+rotation,()=>{const f=frame({rotation,flip:true});const expected=((Math.floor((rotation%360)/90+.5)*90)%360+360)%360;eq(f.rotation,expected);eq(f.flip,true);const clone=new C(f,{rotation:90});eq(clone.rotation,(expected+270)%360);eq(clone.flip,true);f.close();clone.close()});
    await test('structured clone copies bytes and preserves repeated identity',async()=>{const f=frame({rotation:90,flip:true}),c=structuredClone({one:f,two:f});eq(c.one,c.two);eq(c.one.timestamp,-17);eq(c.one.rotation,90);eq(c.one.flip,true);f.close();const b=new Uint8Array(16);await c.one.copyTo(b);eq(b[0],255);c.one.close()});
    await test('transfer closes source including unreferenced frames',()=>{const f=frame(),c=structuredClone(f,{transfer:[f]});eq(f.format,null);eq(c.format,'RGBA');const unused=frame();structuredClone(1,{transfer:[unused]});eq(unused.format,null);c.close()});
    await test('closed frames cannot serialize or transfer',()=>{const f=frame();f.close();throws(globalThis,'DataCloneError',()=>structuredClone(f));throws(globalThis,'DataCloneError',()=>structuredClone(1,{transfer:[f]}))});
    await test('failed serialization preserves live transfer',()=>{const f=frame(),b=new ArrayBuffer(3);throws(globalThis,'DataCloneError',()=>structuredClone({f,fn(){}},{transfer:[f,b]}));eq(f.format,'RGBA');eq(b.byteLength,3);f.close()});
    await test('getter closes unreferenced transfer without detaching buffer',()=>{const f=frame(),b=new ArrayBuffer(3);throws(globalThis,'DataCloneError',()=>structuredClone({get x(){f.close();return 1}},{transfer:[f,b]}));eq(b.byteLength,3)});
    await test('canvas image is copied with timestamp and duration',async()=>{const canvas=new r.OffscreenCanvas(2,1),ctx=canvas.getContext('2d');ctx.fillStyle='red';ctx.fillRect(0,0,2,1);const f=new C(canvas,{timestamp:4,duration:8});ctx.clearRect(0,0,2,1);const b=new Uint8Array(8);await f.copyTo(b,{format:'RGBA'});bytes(b,[255,0,0,255,255,0,0,255]);eq(f.timestamp,4);eq(f.duration,8);f.close();throws(r,'TypeError',()=>new C(canvas));throws(r,'InvalidStateError',()=>new C(new r.OffscreenCanvas(0,1),{timestamp:1}))});
    await test('drawImage honors crop rotation and flip',()=>{const f=frame({rotation:90,flip:true}),canvas=new r.OffscreenCanvas(2,2),ctx=canvas.getContext('2d');ctx.drawImage(f,0,0);bytes(ctx.getImageData(0,0,2,2).data,[255,0,0,255,0,0,255,255,0,255,0,255,255,255,255,255]);f.close();throws(r,'InvalidStateError',()=>ctx.drawImage(f,0,0))});
    await test('createImageBitmap snapshots frame and survives close',async()=>{const f=frame(),p=r.createImageBitmap(f);f.close();const bitmap=await p;eq(bitmap.width,2);eq(bitmap.height,2);const canvas=new r.OffscreenCanvas(2,2),ctx=canvas.getContext('2d');ctx.drawImage(bitmap,0,0);eq(ctx.getImageData(0,0,1,1).data[0],255);bitmap.close()});
  }
  globalThis.__uiEventResults={complete:true,total:checks.length,passed:checks.filter(x=>x.passed).length,checks};
  return checks.every(x=>x.passed);
})()
