async function headersListProbe(base, transport = true, cacheStorage = transport) {
  const checks = [];
  const check = (label, actual, wanted) => {
    if (typeof actual === 'function') {
      try { actual = actual(); } catch (error) { actual = 'throw:' + error.message; }
    }
    checks.push({label, actual, wanted, pass: JSON.stringify(actual) === JSON.stringify(wanted)});
  };
  const cases = [];
  for (const name of ['Accept', 'Accept-Language', 'Content-Language']) {
    for (const [label, values, wanted, mergedAllowed] of [
      ['overflow', ['a'.repeat(126), 'b'], 'a'.repeat(126), false],
      ['at-limit', ['a'.repeat(125), 'b'], 'a'.repeat(125) + ', b', true],
      ['after-limit', ['a'.repeat(125), 'b', 'c'], 'a'.repeat(125) + ', b', false],
      ['empty-first', ['', 'b'.repeat(127)], '', false],
    ]) cases.push([name + '/' + label, name, values, wanted, mergedAllowed]);
  }
  const longType = 'text/plain;x=' + 'a'.repeat(114);
  cases.push(
    ['type/duplicate', 'Content-Type', ['text/plain', 'text/plain'], 'text/plain', false],
    ['type/parameter', 'Content-Type', ['text/plain;charset=utf8', 'extra'], 'text/plain;charset=utf8, extra', true],
    ['type/parameter-second-type', 'Content-Type', ['text/plain;charset=utf8', 'application/json'], 'text/plain;charset=utf8, application/json', true],
    ['type/unsafe', 'Content-Type', ['text/plain;charset=utf8', '"'], 'text/plain;charset=utf8', false],
    ['type/invalid-first', 'Content-Type', ['application/json', 'text/plain'], 'text/plain', false],
    ['type/overflow', 'Content-Type', [longType, 'ok'], longType, false],
  );
  for (const [label, name, values, wanted, mergedAllowed] of cases) {
    const names = [name, name.toLowerCase(), name.toUpperCase()];
    const pairs = values.map((value, index) => [names[index], value]);
    const url = base + '/echo?case=' + encodeURIComponent(label);
    const source = new Request(url, {headers: pairs});
    const joined = values.join(', ');
    const refill = request => new Request(request, {mode: 'no-cors'});
    check(label + '/mode-change', refill(source).headers.get(name), wanted);
    check(label + '/clone-refill', refill(source.clone()).headers.get(name), wanted);
    check(label + '/construct-copy', refill(new Request(source)).headers.get(name), wanted);
    check(label + '/refill-cors', refill(new Request(source, {cache: 'no-store'})).headers.get(name), wanted);
    check(label + '/input-unmodified', source.headers.get(name), joined);
    check(label + '/guarded-clone', refill(source).clone().headers.get(name), wanted);
    check(label + '/public-headers-init', new Request(url, {mode: 'no-cors', headers: source.headers}).headers.get(name), mergedAllowed ? joined : null);
    source.headers.append('X-Unrelated', 'value');
    check(label + '/after-unrelated-mutation', refill(source).headers.get(name), wanted);
    if (transport) {
      for (const [kind, input, init, expected] of [
        ['mode', source, {mode: 'no-cors'}, wanted],
        ['clone', source.clone(), {mode: 'no-cors'}, wanted],
        ['refilled', refill(source), undefined, wanted],
        ['cors', source, undefined, joined],
      ]) {
        let actual;
        try { actual = new Headers((await (await fetch(input, init)).json()).headers).get(name); }
        catch (error) { actual = 'throw:' + error.message; }
        check(label + '/fetch-' + kind, actual, expected);
      }
    }
  }

  // Mutating another name must not trim separators generated by empty fields.
  const pairs = [['X-B', 'b'], ['X-A', ' a '], ['Set-Cookie', 'a=1'], ['x-a', ''], ['X-A', ''], ['set-cookie', 'b=2']];
  const headers = new Headers(pairs);
  headers.append('X-C', 'c');
  headers.set('X-B', 'new');
  headers.delete('X-C');
  const expectedEntries = [['set-cookie', 'a=1'], ['set-cookie', 'b=2'], ['x-a', 'a, , '], ['x-b', 'new']];
  check('projection/get', headers.get('x-a'), 'a, , ');
  check('projection/entries', [...headers], expectedEntries);
  check('projection/keys', [...headers.keys()], expectedEntries.map(entry => entry[0]));
  check('projection/values', [...headers.values()], expectedEntries.map(entry => entry[1]));
  check('projection/cookies', headers.getSetCookie(), ['a=1', 'b=2']);
  const visited = [];
  headers.forEach((value, key, owner) => visited.push([key, value, owner === headers]));
  check('projection/forEach', visited, expectedEntries.map(entry => [...entry, true]));
  check('projection/public-copy-normalizes', new Headers(headers).get('x-a'), 'a, ,');
  const iterator = headers.entries();
  check('projection/live-first', iterator.next().value, expectedEntries[0]);
  headers.append('X-B', 'tail');
  check('projection/live-rest', [...iterator], [expectedEntries[1], expectedEntries[2], ['x-b', 'new, tail']]);
  headers.set('x-a', 'reset');
  headers.append('X-A', 'end');
  check('projection/set-replaces-all', headers.get('x-a'), 'reset, end');
  headers.delete('x-a');
  check('projection/delete-all', headers.has('x-a'), false);
  const response = new Response(null, {headers: pairs});
  response.headers.append('x-other', 'value');
  const responseCopy = response.clone();
  responseCopy.headers.set('x-b', 'changed');
  check('response/original-empty-values', response.headers.get('x-a'), 'a, , ');
  check('response/clone-empty-values', responseCopy.headers.get('x-a'), 'a, , ');
  check('response/clone-isolated', response.headers.get('x-b'), 'b');

  const long = 'a'.repeat(126);
  for (const poisoned of ['request-getter', 'headers-iterator', 'both']) {
    const request = new Request(base + '/echo?case=' + poisoned, {headers: [['Accept', long], ['accept', 'b']]});
    const associated = request.headers;
    let getterCalls = 0;
    let iteratorCalls = 0;
    if (poisoned !== 'headers-iterator') {
      Object.defineProperty(request, 'headers', {get() { getterCalls++; throw new Error('headers getter'); }});
    }
    if (poisoned !== 'request-getter') {
      Object.defineProperty(associated, Symbol.iterator, {get() { iteratorCalls++; throw new Error('headers iterator'); }});
    }
    check(poisoned + '/inherit', () => new Request(request).headers.get('Accept'), long + ', b');
    check(poisoned + '/refill', () => new Request(request, {mode: 'no-cors'}).headers.get('Accept'), long);
    check(poisoned + '/clone', () => request.clone().headers.get('Accept'), long + ', b');
    if (transport) {
      let actual;
      try { actual = new Headers((await (await fetch(request, {mode: 'no-cors'})).json()).headers).get('Accept'); }
      catch (error) { actual = 'throw:' + error.message; }
      check(poisoned + '/fetch', actual, long);
    }
    check(poisoned + '/getter-not-read', getterCalls, 0);
    check(poisoned + '/iterator-not-read', iteratorCalls, 0);
    if (poisoned !== 'request-getter') {
      check(poisoned + '/explicit-init-observes-iterator', () => new Request(base, {headers: associated}), 'throw:headers iterator');
      check(poisoned + '/explicit-init-reads-once', iteratorCalls, 1);
    }
  }

  for (const stream of [false, true]) {
    const body = stream ? new ReadableStream({start(controller) { controller.enqueue(new Uint8Array([65])); controller.close(); }}) : 'A';
    const source = new Request(base, {method: 'POST', body, duplex: 'half', headers: [['Accept', long], ['accept', 'b']]});
    const copy = source.clone();
    const refilled = new Request(copy, {mode: 'no-cors', body: 'replacement'});
    check('body/' + stream + '/clone-refill', refilled.headers.get('accept'), long);
    check('body/' + stream + '/replacement', await refilled.text(), 'replacement');
    check('body/' + stream + '/original', await source.text(), 'A');
  }

  // Cache stores copies of Requests and Responses, including their header lists.
  if (cacheStorage) {
    const cacheName = 'headers-list-' + Math.random().toString(36);
    try {
      const cache = await caches.open(cacheName);
      const url = base + '/cached';
      const request = new Request(url, {headers: [['Accept', long], ['accept', 'b']]});
      await cache.put(request, new Response('stored', {headers: [['Vary', 'Accept'], ['X-List', 'first'], ['x-list', '']]}));
      const keys = await cache.keys();
      check('cache/key-refill', new Request(keys[0], {mode: 'no-cors'}).headers.get('Accept'), long);
      const match = await cache.match(new Request(url, {headers: {Accept: long + ', b'}}));
      check('cache/vary-combined-match', await match.text(), 'stored');
      check('cache/response-fields', match.headers.get('x-list'), 'first, ');
      check('cache/vary-mismatch', await cache.match(new Request(url, {headers: {Accept: long}})), undefined);
    } finally { await caches.delete(cacheName); }
  }
  return {state: checks.every(check => check.pass) ? 'pass' : 'fail', checks};
}
